### ISSUE TITLE
[Bug] FPS drops and game crashes in netherland

### ISSUE THREAD

**Issue by ColinIsWorking** [RyanGar46/Classic-3D#18] opened 2022-12-26 12:41 UTC
**READ THIS**
**Please put the labels that best fit with this bug. For example put "Classic 3D - Lite" if it only applies to classic 3d lite.**
[Classic 3D v15.1 - 1.19]
**Describe the bug**
My version is 1.19.2. I'm running"Classic 3D v15.1 - 1.19". Every time I enter Netherland, the graphics suddenly freeze and the game crashes. Pleaseeeeeee fix the bug!!

**To Reproduce**
1. Using 1.19.2, Forge43.2.1, Optifine_H9
2. Enter the netherland
3. See error

**Expected behavior**
 the graphics suddenly freeze and the game crashes

**Screenshots**
You can't see the bug in a screenshot

**Info (please complete the following information):**
 - Minecraft Version: 1.19.2
 - Classic 3D Version: v15.2

**Additional context**

**Comment by RyanGar46** [comment] 2023-01-25 21:26
Duplicate of #8

**Closed by RyanGar46** 2023-01-25 21:26 UTC
Labels: bug
