### ISSUE TITLE
[Performance] [Classic 3D] Nether Instabilities 

### ISSUE THREAD

**Issue by JackiTacki** [RyanGar46/Classic-3D#20] opened 2023-02-09 13:47 UTC
**Describe the bug**
Performance Difficulties;

Naturally, The game runs at least around 100-140 frames in the overworld, Not bad considering my shaders and I'm fine with that. However, The nether is where everything hitches and takes a crash to itself; In which, Performance can become absolutely unplayable in most instances whilst loading new chunks. Some may have already noted this. 

It sucks, Seeing how much I love this pack. 

***SPECS***
AMD Ryzen 7 5800X
AMD Radeon RX 6700 XT
[Capable of Sodium-Iris at 190-300FPS]

**To Reproduce**
1. Launch Minecraft 1.19.3 
2. Find a world.
3. Enter the Nether.
4. Load chunks. Simple. 

**Expected behavior**
Some form of actual playability.

**Info (please complete the following information):**
 - Minecraft Version: V1.19.3
 - Classic 3D Version: V15.2

***SOLUTION REFERENCE***
My recommendation is perhaps alternating/updating the Lite version, So we can still have things like the more commonly used materials planks and torches, utility items, etc without the more extensive things. Or, If able, Optimize further?

**Comment by RyanGar46** [comment] 2023-02-09 16:15
Duplicate of #8

**Closed** 2023-02-09 16:15 UTC
Labels: bug, duplicate
